dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
install: pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 jumpcutter.py --url https://youtu.be/fazSo3R6tIw --silent_speed 999999 --sounded_speed 2|| python jumpcutter.py --url https://youtu.be/fazSo3R6tIw --silent_speed 999999 --sounded_speed 2
